//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjesiSonGün.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ebeveyn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ebeveyn()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public int EbeveynID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Gelir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
