//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjesiSonGün.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int KayitID { get; set; }
        public Nullable<int> CocukID { get; set; }
        public Nullable<int> EbeveynID { get; set; }
        public string CocukAlmaDurumu { get; set; }
    
        public virtual Cocuk Cocuk { get; set; }
        public virtual Ebeveyn Ebeveyn { get; set; }
    }
}
